### PR TITLE
fix(android): UTF-8 encode form data value

### LINKED ISSUE #7526: [Bug]: multipart/form-data values are not encoded on Android
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 5.7.5
  @capacitor/core: 5.7.6
  @capacitor/android: 5.7.6
  @capacitor/ios: 5.7.6

[success] Android looking great! 👌
[error] Xcode is not installed

### Other API Details

```Shell
$ npm --version
10.5.0
$ node --version
v20.12.1
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

When using multipart/form-data in a POST request on Android, the values are not encoded, which is problematic when the values contain accents or emojis for example

On the web and on iOS the values are correctly encoded

### Expected Behavior

Accents should be correctly encoded on Android

### Project Reproduction

https://github.com/malo-malo/capacitor-android-encoding

### Additional Information

I have fixed the issue for my case, and opened a merge request with my solution, so it can be used by everyone
https://github.com/ionic-team/capacitor/pull/7525

### PR DESCRIPTION
**Pull request by malo-malo**
When using multipart/form-data in a POST request on Android, the values are not encoded, which is problematic when the values contain accents or emojis for example
This merge request proposes to encode values in UTF-8, similar to what is done when encoding other POST requests body

Fixes #7526 
closes https://github.com/ionic-team/capacitor/pull/7219
closes https://github.com/ionic-team/capacitor/pull/6730

### CODE REVIEW

File: android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java [hunk 1]
```diff
@@ -275,7 +275,7 @@ private void writeFormDataRequestBody(String contentType, JSArray entries) throw
                     if (type.equals("string")) {
                         os.writeBytes(twoHyphens + boundary + lineEnd);
                         os.writeBytes("Content-Disposition: form-data; name=\"" + key + "\"" + lineEnd + lineEnd);
-                        os.writeBytes(value);
+                        os.write(value.getBytes("UTF-8"));
```
Comment (jcesarmobile) [inline android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java:278]:
```suggestion
                        os.write(value.getBytes(StandardCharsets.UTF_8));
```
Can you use `StandardCharsets.UTF_8` instead of hardcoding `"UTF-8"`?

**Review by jcesarmobile — APPROVED** [review]

**Review by markemer — APPROVED** [review]
